// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFGrq8KBC_N9UsOKDKMaD3wxMC6aXE66U',
    appId: '1:418197683207:web:a627aca120e765b7f83ea2',
    messagingSenderId: '418197683207',
    projectId: 'fir-flutter-codelab-f4293',
    authDomain: 'fir-flutter-codelab-f4293.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-f4293.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVFpv3pBJZog0s_JSG66ohozs0PAHlBbI',
    appId: '1:418197683207:android:a8c99fcfa430d670f83ea2',
    messagingSenderId: '418197683207',
    projectId: 'fir-flutter-codelab-f4293',
    storageBucket: 'fir-flutter-codelab-f4293.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX8cFGSc0JBF2kiyTw3h2N05bQ42FqHKg',
    appId: '1:418197683207:ios:e9601e5a84c9f9d7f83ea2',
    messagingSenderId: '418197683207',
    projectId: 'fir-flutter-codelab-f4293',
    storageBucket: 'fir-flutter-codelab-f4293.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX8cFGSc0JBF2kiyTw3h2N05bQ42FqHKg',
    appId: '1:418197683207:ios:e9601e5a84c9f9d7f83ea2',
    messagingSenderId: '418197683207',
    projectId: 'fir-flutter-codelab-f4293',
    storageBucket: 'fir-flutter-codelab-f4293.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
